# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("update_geom_font_defaults works", {
  expect_true(inherits(update_geom_font_defaults, "function")) 
})
