# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("package_font_registered works", {
  expect_true(inherits(package_font_registered, "function")) 
})
