# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("render_digest works", {
  expect_true(inherits(render_digest, "function")) 
})
