# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Apply IOM theme to a ggplot object
#'
#' Adds thematic presets adhering to the IOM visual branding to a ggplot object.
#' The function adjusts text sizes, colors, legend positioning, panel grids,
#' and other visual elements based on the specified plot type.
#'
#' The `basesize` parameter controls the base font size for axis labels, titles,
#' and plot annotations. The `font` parameter sets the font family.
#' The `facets` parameter specifies whether the plot uses faceting, which adjusts
#' the strip appearance accordingly.
#'
#' Supported plot types:
#' \itemize{
#'   \item `"line"` - Line plots with appropriate legend keys and grid lines.
#'   \item `"bar-horizontal"` - Horizontal bar plots with grid on x-axis.
#'   \item `"bar-vertical"` - Vertical bar plots with grid on y-axis.
#'   \item `"scatter"` - Scatter plots with grid lines.
#'   \item `"map"` - Map plots with minimal axis text and no grid.
#'   \item `"void"` - Empty theme (not implemented here, but can be added).
#' }
#'
#' @param type Character. Type of plot to theme. One of "line", "bar-horizontal",
#'   "bar-vertical", "scatter", "map", or "void".
#' @param basesize Numeric. Base font size in points. Default is 7.
#' @param font Character. Font family for all text elements. Default is "Gill Sans Nova".
#' @param facets Logical. Whether the plot is faceted. Default is FALSE.
#'
#' @return A list of ggplot2 theme elements to be added to a ggplot object.
#' 
#' @importFrom ggplot2 theme element_text element_blank 
#'                    element_line element_rect margin unit
#' @importFrom grid unit 
#' @export
#' @examples
#' library(ggplot2)
#'
#' # Simple scatter plot with IOM theme
#' p <- ggplot(mpg, aes(displ, hwy, color = class)) +
#'   geom_point() +
#'   labs(
#'     title = "Scatter Plot with IOM Theme",
#'     caption = "Source: mpg dataset"
#'   ) +
#'   apply_theme(type = "scatter", basesize = 9)
#'
#' p

apply_theme <- function(type,
                        basesize = 7,
                        font = "Open Sans",
                        facets = FALSE) {



  # Define a simple color palette function stub
  pal <- function(name = "blues", n = 5) {
    # This is a stub; replace with your actual palette function.
    # Here we return a vector of hex colors for 'blues'
    blues <- c("#f7fbff", "#deebf7", "#9ecae1", "#3182bd", "#08519c")
    if (n > length(blues)) n <- length(blues)
    return(blues[seq_len(n)])
  }

  # Size parameters
  size <- list(
    text = basesize,
    title = basesize + 2,
    stext = basesize - 1,
    footnote = basesize - 2
  )

  # Scaling function for margins and line widths
  k <- function(factor = 1) factor * size$text / .pt

  panel_grid_color <- pal("blues", 5)[4]
  panel_grid_width <- k(0.1)
  bar_key_size <- grid::unit(1.25 * size$text, "points")
  line_key_height <- grid::unit(size$text, "points")
  line_key_width <- grid::unit(2 * size$text, "points")
  steps_key_height <- grid::unit(0.75 * size$text, "points")
  steps_key_width <- grid::unit(2 * size$text, "points")

  base <- theme(
    text = element_text(family = font, color = pal("blues")[5]),

    axis.title = element_blank(),
    axis.text = element_text(size = size$text, color = pal("blues")[5]),
    axis.ticks = element_blank(),

    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.key.spacing.y = grid::unit(0 * size$text, "points"),
    legend.text = element_text(
      size = size$text,
      margin = margin(r = k(0.5), l = k(1))
    ),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.box.margin = margin(t = k(-3), b = k(-3)),

    panel.background = element_blank(),
    panel.border = element_blank(),
    panel.grid.minor = element_blank(),

    plot.background = element_blank(),
    plot.title = element_text(
      face = "bold",
      size = size$title,
      hjust = 0.5,
      margin = margin(b = k(3.5))
    ),
    plot.title.position = "plot",
    plot.caption = element_text(
      face = "italic",
      color = pal("blues")[3],
      size = size$text,
      hjust = 0,
      lineheight = 1.2,
      margin = margin(t = k(3.5), r = k(1), l = k(1))
    ),
    plot.caption.position = "plot",
    plot.margin = margin(k(1), k(2), k(1), k(2))
  )

  theme <- base

  if (type == "bar-horizontal") {
    theme_barh <- theme(
      legend.key.size = bar_key_size,
      panel.grid.major.x = element_line(
        linewidth = panel_grid_width,
        color = panel_grid_color
      ),
      panel.grid.major.y = element_blank()
    )
    theme <- theme + theme_barh
  } else if (type == "bar-vertical") {
    theme_barv <- theme(
      legend.key.size = bar_key_size,
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(
        linewidth = panel_grid_width,
        color = panel_grid_color
      )
    )
    theme <- theme + theme_barv
  } else if (type == "line") {
    theme_line <- theme(
      legend.key.height = line_key_height,
      legend.key.width = line_key_width,
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(
        linewidth = panel_grid_width,
        color = panel_grid_color
      )
    )
    theme <- theme + theme_line
  } else if (type == "scatter") {
    theme_scat <- theme(
      legend.key.size = bar_key_size,
      panel.grid.major = element_line(
        linewidth = panel_grid_width,
        color = panel_grid_color
      )
    )
    theme <- theme + theme_scat
  } else if (type == "map") {
    theme_map <- theme(
      axis.text = element_blank(),
      legend.key.height = steps_key_height,
      legend.key.width = steps_key_width,
      legend.text = element_text(
        size = size$stext,
        margin = margin(t = k(1.5))
      ),
      panel.grid.major = element_blank()
    )
    theme <- theme + theme_map
  } else if (type == "void") {
    # You can define an empty theme here if needed
    theme <- theme_void()
  } else {
    warning("Unknown theme type, returning base theme.")
  }

  if (facets) {
    theme_facets <- theme(
      strip.background = element_rect(fill = NA),
      strip.text = element_text(
        size = size$title,
        color = pal("blues")[5],
        margin = margin(b = k(3.5))
      )
    )
    theme <- theme + theme_facets
  }

  return(theme)
}
