# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate a Preset Plot or Retrieve Plot Metadata
#'
#' This function generates a ggplot object for a specified plot `key` and country ISO3 code,
#' or returns the plot's metadata if `iso` is `NULL`.
#'
#' @param key Character. The plot key identifying which plot to generate.
#'   Must correspond to a function named `plot_<key>` in the `amerdigest` package.
#' @param iso Character or NULL. ISO3 country code for which to generate the plot.
#'   If `NULL`, the function returns plot metadata instead of a plot.
#' @param ... Additional arguments passed to the plot generating function.
#'
#' @return A `ggplot` object if `iso` is provided, or a list containing plot metadata if `iso` is `NULL`.
#'
#' @importFrom cli cli_abort
#' @import ggplot2 
#' @export
#' @examples
#' # Generate a plot for USA
#' p1 <- digest_plot(key="regflow", iso = "USA")
#'
#' p1
#' # Test error catching
#' p2 <- digest_plot(key="regnet", iso = "USA")
#' p2
#'

digest_plot <- function(key,
                        iso = NULL,
                        ...) {

  plotter_name <- paste0("plot_", key)

  # Check if plot function exists
  if (!exists(plotter_name, envir = asNamespace("amerdigest"), inherits = FALSE)) {
    cli::cli_abort("{.val {key}} is not a valid plot key.")
  }

  plotter <- get(plotter_name, envir = asNamespace("amerdigest"))

  # If iso is NULL, return plot metadata (assuming the plotter supports this)
  if (is.null(iso)) {
    #if ("metadata" %in% names(formals(plotter))) {
    #  return(plotter(metadata = TRUE, ...))
    #} else {
      # If no metadata argument, return NULL or throw informative message
      cli::cli_abort("Plot metadata is not available for {.val {key}}.")
    #}
  }

  # Validate iso
  if (!(iso %in% countrynames$iso3)) {
    cli::cli_abort("{.val {iso}} is not a valid ISO3 code.")
  }

  # Generate and return plot
  plotter(iso, ...)
}
