# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

' Prepare Regional Flow Data for Charts
#'
#' Aggregates and combines registration inflow and outflow data.
#'
#' @param iso Optional character. ISO3 country code to filter the data by geography.
#'   If NULL (default), returns data for all geographies.
#'
#' @return A data frame with columns `geo`, `t`, `n`, and `var`, where `var` indicates
#'   whether the count is "Entries" or "Exits".
#'
#' @importFrom dplyr bind_rows summarise mutate filter
#' @importFrom stats setNames
#' @export
#' @examples
#' # Get all regional flows
#' all_flows <- get_regflow()
#'
#' knitr::kable(head(all_flows,5))
#'
#' # Get flows for USA only
#' usa_flows <- get_regflow("USA")
#'
#' knitr::kable(head(usa_flows,5))

get_regflow <- function(iso = NULL) {
  # Aggregate inflow entries
  entries <- regin |>
    summarise(n = sum(n), .by = c(geo, t)) |>
    mutate(var = "Entries")

  # Aggregate outflow exits
  exits <- regout |>
    summarise(n = sum(n), .by = c(geo, t)) |>
    mutate(var = "Exits")

  # Combine entries and exits
  data <- bind_rows(entries, exits)

  # Filter by iso if provided
  if (!is.null(iso)) {
    data <- filter(data, geo == iso)
  }

  return(data)
}
