# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Prepare Regional Net Registration Data for Charts
#'
#' Calculates net registrations by subtracting outflows from inflows aggregated by geography and time.
#'
#' @param iso Optional character. ISO3 country code to filter the data by geography.
#'   If NULL (default), returns data for all geographies.
#'
#' @return A data frame with columns `t`, `geo`, `n_in`, `n_out`, and `n` where `n` is net registrations.
#'
#' @importFrom dplyr full_join summarise mutate filter
#' @importFrom tidyr  drop_na
#' @export
#' @examples
#' # Get net registrations for all geographies
#' net_all <- get_regnet()
#'
#' knitr::kable(head(net_all,5))
#' # Get net registrations for USA only
#'
#' net_usa <- get_regnet("USA")
#'
#' knitr::kable(head(net_usa,5))

get_regnet <- function(iso = NULL) {
  inflows <- regin |>
    dplyr::summarise(n_in = sum(n), .by = c(geo, t))

  outflows <- regout |>
    dplyr::summarise(n_out = sum(n), .by = c(geo, t))

  # Join inflows and outflows by time and geography
  data <- dplyr::full_join(inflows, outflows, by = c("t", "geo")) |>
    tidyr::drop_na() |>
    dplyr::mutate(n = n_in - n_out)

  # Filter by iso if provided
  if (!is.null(iso)) {
    data <- dplyr::filter(data, geo == iso)
  }

  return(data)
}
