# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Check if Open Sans font is registered through \code{extrafont}
#'
#' Verify if Open Sans is registered through \code{extrafont}
#'
#' @importFrom systemfonts system_fonts
#' @importFrom extrafont fonts
#'
#' @returns TRUE if OpenSans, Arial and Gill Sans Nova are registered
#' @export
#' @examples
#' package_font_registered()

package_font_registered <- function() {
  any(grepl("Gill Sans Nova", extrafont::fonts(), ignore.case = TRUE))
  suppressMessages(extrafont::loadfonts())
}
