# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Choose an IOM Color Palette Shade
#'
#' Returns one or more hex color codes from predefined IOM color palettes.
#'
#' @param color Character. Name of the color palette. Must be one of
#'   `"blues"`, `"unblues"`, `"yellows"`, `"greens"`, `"oranges"`, `"reds"`, or `"grays"`.
#' @param shade Integer vector. Shade(s) to select from 1 (darkest) to 5 (lightest).
#'   Can be a single number or a vector of shades.
#'
#' @return Character vector of hex color codes corresponding to the selected shades.
#'
#' @export
#' @examples
#' pal("blues")
#' pal("reds", c(1, 3, 5))
pal <- function(color, shade = 1) {
  # Define palettes with hex color codes
  palette <- list(
    blues    = c("#0033A0", "#4068B8", "#8099D0", "#B3C2E3", "#D9E0F1"),
    unblues  = c("#418FDE", "#84ADEC", "#ADC9F2", "#CEDEF7", "#E6EFFB", "#F4F8FD"),
    yellows  = c("#FFB81C", "#FFCA55", "#FFDC8E", "#FFEABB", "#FFF4DD"),
    greens   = c("#5CB8B2", "#85CAC5", "#AEDCD9", "#CEEAE8", "#E7F4F3"),
    oranges  = c("#FF671F", "#FF8D57", "#FFB38F", "#FFD1BC", "#FFE8DD"),
    reds     = c("#D22630", "#DD5C64", "#E99398", "#F2BEC1", "#F8DEE0"),
    grays    = c("#404040", "#666666", "#999999", "#CCCCCC", "#F2F2F2")
  )

  # Check if color exists in palette
  if (!color %in% names(palette)) {
    stop(sprintf("Color '%s' not found. Choose from: %s", color, paste(names(palette), collapse = ", ")))
  }

  # Validate shade values
  max_shade <- length(palette[[color]])
  if (any(shade < 1 | shade > max_shade)) {
    stop(sprintf("Shade values must be between 1 and %d for color '%s'.", max_shade, color))
  }

  # Return colors for given shade indices
  colors <- palette[[color]][shade]

  return(colors)
}

