# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Format numbers with pretty labels
#'
#' These wrapper functions apply the `prettylabel` function with preset options
#' for formatting numbers, currencies, and percentages in plots or tables.
#'
#' Note: This assumes you have a function named `prettylabel` available in your environment.
#' If not, please provide or load it.
#'
#' @param num Numeric vector or single number to format.
#' @return Character vector of formatted numbers.
#' @export
#' @examples
#' # Example usage if prettylabel is defined
#' pl(c(1234, 56789))

pl <- function(num) prettylabel(num, signif = 2, spell = TRUE)

#' @rdname pl
pl1 <- function(num) prettylabel(num, signif = 2, spell = TRUE)

#' @rdname pl
pl_usd <- function(num) prettylabel(num, spell = TRUE, currency = "\\$")

#' @rdname pl
pl_pct <- function(num) prettylabel(num, signif = 2, pct = TRUE)

#' @rdname pl
pl_pct1 <- function(num) prettylabel(num, signif = 2, pct = TRUE)
