# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regular Entries and Exits
#'
#' @param iso ISO3 country code.
#' @param basesize Base font size. Default is 7.
#' @param font Font family. Default is "Open Sans".
#' @param title Plot title. Default is "Regular entries and exits".
#' @import ggplot2
#' @importFrom tsibble scale_x_yearmonth
#'
#' @return A ggplot2 object.
#' @export
#' @examples
#' plot_regflow("PAN")
plot_regflow <- function(iso,
                         basesize = 7,
                         font = "Open Sans",
                         title = "Regular entries and exits") {

  k <- function(factor = 1) factor * basesize / .pt
  source <- "Source: IOM Lighthouse Project."
  data <- digest_data("regflow", iso)

  if (nrow(data) > 0) {
    axis <- set_axis(data$n, "Persons")

    plot <- ggplot(data, aes(x = t, y = n, group = var, color = var)) +
      geom_line(linewidth = k(0.25)) +
      geom_hline(yintercept = 0, color = pal("blues"), linewidth = k(0.1)) +
      labs(title = title, caption = source) +

      tsibble::scale_x_yearmonth(
        date_breaks = "1 year",
        date_minor_breaks = "3 months",
        date_labels = "%Y",
        expand = expansion(mult = c(0, 0.03)),
        guide = guide_axis(minor.ticks = TRUE)
      ) +
      scale_y_continuous(
        name = axis$title,
        breaks = axis$breaks,
        labels = axis$labels
      ) +
      scale_color_manual(values = c(pal("blues", 2), pal("greens"))) +

      apply_theme("line", basesize = basesize, font = font) +
      theme(
        axis.title.y = element_text(size = basesize, margin = margin(r = k(2))),
        axis.ticks.x = element_line(color = pal("blues"), linewidth = k(0.05))
      )

  } else {
    plot <- plot_empty(title, source, basesize, font)
  }

  return(plot)
}
