# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Net Regular Entries
#'
#' @param iso ISO3 country code.
#' @param basesize Base font size. Default is 7.
#' @param font Font family. Default is "Open Sans".
#' @param title Plot title. Default is "Net regular entries".
#' 
#' @import ggplot2
#' @importFrom tsibble scale_x_yearmonth
#' 
#' @return A ggplot2 object.
#' @export
#' @examples
#' plot_regnet("BRA", title = "Custom Net Entry Title")
plot_regnet <- function(iso,
                        basesize = 7,
                        font = "Open Sans",
                        title = "Net regular entries") {

  k <- function(factor = 1) factor * basesize / .pt
  source <- "Source: IOM Lighthouse Project."
  data <- digest_data("regnet", iso)

  if (nrow(data) > 0) {
    axis <- set_axis(data$n, "Persons")

    plot <- ggplot(data, aes(x = t, y = n)) +
      geom_bar(
        stat = "identity",
        fill = ifelse(data$n >= 0, pal("blues", 2), pal("greens"))
      ) +
      geom_hline(yintercept = 0, color = pal("blues"), linewidth = k(0.1)) +
      labs(title = title, caption = source) +

      tsibble::scale_x_yearmonth(
        date_breaks = "1 year",
        date_minor_breaks = "3 months",
        date_labels = "%Y",
        expand = expansion(mult = c(0.03, 0.03)),
        guide = guide_axis(minor.ticks = TRUE)
      ) +
      scale_y_continuous(
        name = axis$title,
        breaks = axis$breaks,
        labels = axis$labels
      ) +

      apply_theme("bar-vertical", basesize = basesize, font = font) +
      theme(
        axis.title.y = element_text(size = basesize, margin = margin(r = k(2))),
        axis.ticks.x = element_line(color = pal("blues"), linewidth = k(0.05))
      )

  } else {
    plot <- plot_empty(title, source, basesize, font)
  }

  return(plot)
}
