# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Add Label to Top of ggplot Object
#'
#' Adds a styled label with a colored background to the top of a plot using `cowplot`.
#' Useful for annotating subplots with country names, indicators, or categories.
#'
#' @param plot A ggplot object to be labeled.
#' @param label A string to display as the label.
#' @param span Integer (1, 2, or 3) controlling the width of the label box.
#' @param h Numeric height of the label box relative to the plot (default = 0.06).
#' @param basesize Numeric. Base font size in points. Default is 7.
#' @param font Character. Font family for all text elements. Default is "Gill Sans Nova".
#' @return A ggdraw object (from the `cowplot` package) with the label applied.
#'
#' @importFrom cowplot ggdraw draw_label draw_grob
#' @importFrom grid rectGrob gpar
#'
#' @export
#' @examples
#' library(ggplot2)
#' p <- ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point()
#' plot_label(p, "Fuel Efficiency", span = 2)
plot_label <- function(plot, label, span = 2, h = 0.06, basesize = 7, font = "Open Sans") {

  box <- grid::rectGrob(gp = grid::gpar(fill = pal("unblues", 3), col = NA))

  width <- 0.025 + 0.015 * nchar(label)
  height <- h
  if (span == 1) width <- width / 2
  if (span == 3) width <- width * 1.5

  p <- cowplot::ggdraw(plot) +
    cowplot::draw_grob(
      box,
      x = 0,
      y = 1,
      vjust = 1,
      width = width,
      height = height
    ) +
    cowplot::draw_label(
      label,
      x = width / 2,
      y = 1 - height / 2,
      hjust = 0.5,
      vjust = 0.5,
      size = basesize,
      fontface = "bold",
      fontfamily = font,
      color = "white"
    )
  
  return(p)
}
