# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate an Empty Placeholder Plot
#'
#' @param title Plot title.
#' @param source Data source caption.
#' @param basesize Base font size. Default is 7.
#' @param font Font family. Default is "Open Sans".
#' @param msg Message to display. Default is "No data".
#' @importFrom cowplot ggdraw draw_label draw_grob
#' @importFrom grid rectGrob gpar
#'
#' @return A ggplot2 object with a placeholder message.
#' @export
#' @examples
#' plot_empty("No Data", "Source: Example Org")
plot_empty <- function(title,
                       source,
                       basesize = 7,
                       font = "Open Sans",
                       msg = "No data") {

  k <- function(factor = 1) factor * basesize / .pt

  plot <- ggplot(data.frame(i = 1:10), aes(x = i)) +
    labs(title = title, caption = source) +
    apply_theme("line", basesize = basesize, font = font) +
    theme(
      axis.text = element_blank(),
      panel.background = element_rect(color = NA, fill = pal("unblues", 6)),
      plot.caption = element_text(margin = margin(t = k(), r = k(), l = k()))
    )

  plot <- cowplot::ggdraw(plot) +
    cowplot::draw_label(
      msg,
      y = 0.5,
      fontfamily = font,
      color = pal("blues", 3),
      size = k(3)
    )

  return(plot)
}
