# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Pretty Number Formatting
#'
#' Formats numbers for display in charts and tables. Supports abbreviation
#' (e.g., thousands, millions), spelling out large numbers, adding percent
#' or currency signs, and controlling decimal padding.
#'
#' @param N A number or numeric vector to be formatted.
#' @param signif Number of significant digits to retain. Must be > 0. Default is 2.
#' @param shorten Logical. If `TRUE`, abbreviates long numbers (e.g., 1,200 → "1.2K").
#'        Currently not used directly but preserved for backward compatibility.
#' @param spell Logical. If `TRUE`, spells out large values (e.g., "million" instead of "M").
#' @param padzero Logical. If `TRUE`, pads decimals to reach the requested precision.
#' @param pct Logical. If `TRUE`, appends a percent sign or " per cent" if `spell = TRUE`.
#' @param currency Optional string (e.g., "$", "€") to prepend as a currency symbol.
#'
#' @return A character vector of formatted number labels.
#'
#' @importFrom cli cli_abort
#'
#' @export
#'
#' @examples
#'
#' prettylabel(123456)                      # "123K"
#'
#' prettylabel(123456789, spell = TRUE)     # "123 million"
#'
#' prettylabel(0.756, pct = TRUE)           # "75.6%"
#'
#' prettylabel(1200, currency = "$")        # "$1.2K"
#'
#' prettylabel(c(1e6, 2e9), signif = 3)     # "1.00M" "2.00B"
#'
#' prettylabel(NA)                          # NA
#'
#'

prettylabel <- function(N,
                        signif = 2,
                        shorten = TRUE,  # Not used, included for legacy interface
                        spell = FALSE,
                        padzero = FALSE,
                        pct = FALSE,
                        currency = NULL) {

  if (signif <= 0) {
    cli::cli_abort("`signif` must be greater than zero.")
  }

  fmt <- function(num) {
    parts <- strsplit(as.character(num), "\\.")[[1]]
    units <- nchar(parts[1])
    decimals <- ifelse(is.na(parts[2]), 0, nchar(parts[2]))

    digits <- signif
    if (units > signif) digits <- units
    num <- signif(num, digits = digits)

    nsmall <- 0
    if (padzero && (units + decimals < signif)) {
      nsmall <- signif - units
    }

    format(
      num,
      digits = signif,
      nsmall = nsmall,
      trim = TRUE,
      big.mark = ",",
      scientific = FALSE
    )
  }

  suffixes <- if (spell) {
    list(
      pc = " per cent",
      mn = " million",
      bn = " billion",
      tn = " trillion"
    )
  } else {
    list(
      pc = "%",
      th = "K",
      mn = "M",
      bn = "B",
      tn = "T"
    )
  }

  labels <- character(length(N))

  for (i in seq_along(N)) {
    n <- N[i]

    if (is.na(n)) {
      labels[i] <- NA
      next
    }

    label <- list(
      prefix = if (is.null(currency)) "" else currency,
      number = NULL,
      suffix = NULL
    )

    if (pct) {
      label$number <- fmt(n)
      label$suffix <- suffixes$pc

    } else if (n <= 999.5) {
      label$number <- fmt(n)

    } else if (n >= 999.5 & n < 999500) {
      if (spell) {
        label$number <- fmt(n)
      } else {
        n <- n / 1e3
        label$number <- fmt(n)
        label$suffix <- suffixes$th
      }

    } else if (n >= 999500 & n < 999.5 * 1e6) {
      n <- n / 1e6
      label$number <- fmt(n)
      label$suffix <- suffixes$mn

    } else if (n >= 999.5 * 1e6 & n < 999.5 * 1e9) {
      n <- n / 1e9
      label$number <- fmt(n)
      label$suffix <- suffixes$bn

    } else {
      n <- n / 1e12
      label$number <- fmt(n)
      label$suffix <- suffixes$tn
    }

    labels[i] <- paste0(label$prefix, label$number, label$suffix)
  }

  return(labels)
}
