# WARNING - Generated by {fusen} from dev/flat_my_fun.Rmd: do not edit by hand # nolint: line_length_linter.

#' Set Y-Axis Formatting for Chart Plots
#'
#' Dynamically determines the appropriate Y-axis breaks, labels, and title
#' based on the maximum value in a vector of numeric data. Used to standardize
#' axis formatting across plots.
#'
#' @param values A numeric vector. Typically, a column of values to be plotted.
#' @param units A character string describing the units of measurement (e.g., "Persons", "USD").
#'
#' @return A list with components:
#' \itemize{
#'   \item \code{breaks} — Either a numeric vector or \code{waiver()}.
#'   \item \code{labels} — A labeling function or character vector.
#'   \item \code{title} — A character string for axis title.
#' }
#' @export
#' @examples
#' set_axis(c(100, 500, 1000), units = "Persons")
#' set_axis(c(5e8, 1.5e9), units = "USD")

set_axis <- function(values, units = "Persons") {

  max_n <- max(values, na.rm = TRUE)

  write_title <- function(scale, units) {
    if (units == "USD") paste0(scale, " ", units)
    else paste0(scale, " of ", tolower(units))
  }

  output <- list(
    breaks = waiver(),
    labels = function(x) x / 10^6,
    title = write_title("Millions", units)
  )

  if (max_n < 12) {
    output$title <- units
    output$breaks <- c(0, 5, 10)
    output$labels <- waiver()
  }
  if (max_n >= 12 & max_n < 1200) {
    output$title <- units
    output$labels <- waiver()
  }
  if (max_n >= 1200 & max_n < 1.20e6) {
    output$title <- write_title("Thousands", units)
    output$labels <- function(x) x / 1e3
  }
  if (max_n >= 1.20e6 & max_n < 1.40e6) {
    output$breaks <- seq(0, 1.25e6, 0.25e6)
    output$labels <- c("0", "0.25", "0.50", "0.75", "1.00", "1.25")
  }
  if (max_n >= 1.40e6 & max_n < 1.80e6) {
    output$breaks <- seq(0, 1.50e6, 0.50e6)
    output$labels <- c("0", "0.5", "1.0", "1.5")
  }

  if (max_n >= 1.20e9 & max_n < 1.40e9) {
    output$title <- write_title("Billions", units)
    output$breaks <- seq(0, 1.50e9, 0.25e9)
    output$labels <- c("0", "0.25", "0.50", "0.75", "1.00", "1.25", "1.50")
  }
  if (max_n >= 1.40e9 & max_n < 1.80e9) {
    output$title <- write_title("Billions", units)
    output$breaks <- seq(0, 1.50e9, 0.50e9)
    output$labels <- c("0", "0.5", "1.0", "1.5")
  }
  if (max_n >= 1.80e9) {
    output$title <- write_title("Billions", units)
    output$labels <- function(x) x / 1e9
  }

  return(output)
}
